name: BDProject_USeg

channels:
    - conda-forge
    - anaconda
    
dependencies:
    - python=3.9	
    - pip
    - numpy
    - scipy
    - scikit-image
    - matplotlib-base
    - joblib
    - openpiv
    - napari
