name: USeg

channels:
    - conda-forge
    - anaconda
    
dependencies:
    - python=3.9
    - pyqt=5.12.3
    - pip
    - numpy
    - scipy
    - scikit-image
    - matplotlib-base
    - joblib
    - openpiv
    - napari
